### ISSUE TITLE
ldm/util.py", line 85, in instantiate_from_config     return get_obj_from_str(config["target"])(**config.get("params", dict()))            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: LatentDiffusion.__init__() missing 1 required positional argument: 'cond_stage_config'

### ISSUE THREAD

**Issue by shahzaib-s-warraich** [Gal4way/TPD#5]
Hi, any idea how I might be able to fix this while inferring using ldm's util?

**Comment by Gal4way** [comment]
The information provided currently is a little bit confusing and hard to understand. Could u provide more detailed error messages and the command you inputted so we can help you resolve the issue?

**Comment by shahzaib-s-warraich** [comment]
I'm trying to run inference, `bash commands/inference.sh`, I have the checkpoints, dataset, and stable diffusion repository requirements in place.

**Comment by Baicheng42** [comment]
hi, I got the same error, and I fixed it.

1. I use the easiest way to fix it by replacing the line 18 `sys.path[0] = "/home/yx/code/virtual_tryon/TPD"` in inference.py with **my own path**.

2. then I add the code under it:
if '/home/xxxxx/stable-diffusion' in sys.path:
    sys.path.remove('/home/xxxxx/stable-diffusion/stable-diffusion')`

Then it works for me.

the reason of the ERROR may be due to the conflict between 'stable-diffusion/ldm/util.py' and 'tpd/ldm/util.py' if you installed the package of 'stable-diffusion'.
